# Generated by Django 3.0.8 on 2020-07-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='site_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='site_url',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='feed',
            name='sub_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
