# Generated by Django 3.0.8 on 2020-07-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20200713_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
